language: rust
dist: xenial

rust:
- stable
- beta
- nightly
addons:
  apt:
    packages:
    - doxygen
    - cmake
install:
- git clone https://github.com/BYVoid/OpenCC.git && cd OpenCC
- make PREFIX=/usr && make PREFIX=/usr install
- cd ..