language: rust

rust:
- stable
- beta
- nightly
install:
- sudo apt install -y doxygen cmake
- git clone https://github.com/BYVoid/OpenCC.git && cd OpenCC
- make PREFIX=/usr && make PREFIX=/usr install
- cd ..
os:
- linux